export const data = [
    {
        id: "S201",
        name: "Aman Negi",
        email: "harshchauhan12@gmail.com",
        phone: "+91 9988776655",
        qualification: "B.A",
        class: "11th",
        subjectName:"Aman Negi",
        teacherName:"Saurab Negi",
        chapter:5,
        questions:8,
        marks:30,
        topic:"Angular",
    },
    {
        id: "S202",
        name: "Saurab Negi",
        email: "harshchauhan12@gmail.com",
        phone: "+91 9988776655",
        qualification: "MCA",
        class: "12th",
        subjectName:"Yatharth Negi",
        teacherName:"Saurab Negi",
        chapter:5,
        questions:8,
        marks:30,
        topic:"Angular",
    },
    {
        id: "S203",
        name: "Shubham Pal",
        email: "harshchauhan12@gmail.com",
        phone: "+91 9988776655",
        qualification: "M.TECH",
        class: "10th",
        subjectName:"Aman Negi",
        teacherName:"Saurab Negi",
        chapter:5,
        questions:8,
        marks:30,
        topic:"Angular",
    },
    {
        id: "S204",
        name: "Yatharth Rawat",
        email: "harshchauhan12@gmail.com",
        phone: "+91 9988776655",
        qualification: "B.TECH",
        class: "8th",
        subjectName:"Aman Negi",
        teacherName:"Yatharth Negi",
        chapter:5,
        questions:8,
        marks:30,
        topic:"Angular",
    },
    {
        id: "S205",
        name: "Vikas kumar",
        email: "harshchauhan12@gmail.com",
        phone: "+91 9988776655",
        qualification: "MCA",
        class: "9th",
        subjectName:"Vikas Negi",
        teacherName:"Aman Negi",
        chapter:5,
        questions:8,
        marks:30,
        topic:"Angular",
    },
]